apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: mt-app 

  template:
    metadata:
      labels:
        app: mt-app   

    spec:
      containers:
        - name: mt-app
          image: 713545429153.dkr.ecr.ap-south-2.amazonaws.com/prod/mtapp
          ports:
            - containerPort: 80
